# Data Leakage Construction File - File was created in order to generate PII Information for Datset

In [3]:
import pandas as pd
import numpy as np
import string
import random
import requests

first_names = []
response = requests.get('https://www.mit.edu/~ecprice/wordlist.10000')
for line in response.iter_lines():
    first_names.append(line.decode('utf-8'))

last_names = []
response = requests.get('https://www.mit.edu/~ecprice/wordlist.10000')
for line in response.iter_lines():
    last_names.append(line.decode('utf-8'))


def generate_credit_card_number():
    # Generate a random 15-digit number
    digits = [random.randint(0, 9) for _ in range(15)]
    for i in range(14, -1, -2):
        digits[i] *= 2
        if digits[i] > 9:
            digits[i] -= 9
    check_digit = (10 - sum(digits) % 10) % 10
    return f"{digits[0:4]}-{digits[5:9]}-{digits[10:14]}-{check_digit}"


train_airplane = pd.read_csv('/Users/pedrojosetrujillomejia/Desktop/airplane_test_processed_normalized_date.csv')
test_airplane = pd.read_csv('/Users/pedrojosetrujillomejia/Desktop/airplane_train_processed_date.csv')

combined_dataframe = pd.concat([train_airplane, test_airplane], ignore_index=True)

num_rows = combined_dataframe.shape[0]

first_names = np.random.choice(first_names, num_rows)
last_names = np.random.choice(last_names, num_rows)
credit_cards = np.array([generate_credit_card_number() for i in range(num_rows)])

combined_dataframe['First Name'] = first_names
combined_dataframe['Last Name'] = last_names
combined_dataframe['Credit Card Information'] = credit_cards

In [4]:
combined_dataframe.head()

,Flight Distance,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Female,Gender_Male,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Type of Travel_Business travel,Type of Travel_Personal Travel,Class_Business,...,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,satisfaction,Date,First Name,Last Name,Credit Card Information
0,5.877736,3.044522,2.639057,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,2.0,5.0,4.0,5.0,5.0,satisfied,2017-01-01,amendments,puzzle,"[3, 3, 4, 4]-[1, 4, 4, 1]-[0, 2, 7, 7]-3"
1,6.486161,0.000000,0.000000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,satisfied,2017-01-01,tee,catch,"[2, 8, 0, 0]-[5, 0, 8, 0]-[7, 4, 4, 4]-5"
2,5.568345,0.000000,0.000000,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,5.0,2.0,4.0,5.0,4.0,neutral or dissatisfied,2017-01-01,cu,airfare,"[6, 8, 8, 9]-[4, 8, 5, 0]-[4, 5, 9, 3]-7"
3,6.295266,4.744932,4.663439,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,4.0,4.0,4.0,4.0,1.0,neutral or dissatisfied,2017-01-01,collectors,packaging,"[9, 0, 9, 8]-[1, 2, 3, 5]-[1, 0, 2, 0]-0"
4,7.976252,0.000000,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,...,2.0,2.0,2.0,2.0,1.0,neutral or dissatisfied,2017-01-01,sell,butts,"[5, 5, 4, 3]-[7, 0, 3, 2]-[1, 9, 4, 2]-0"